#! php

<?php

use Symfony\Component\Console\Application;

require "vendor/autoload.php";

$app = new Application("PHPTask", "1.0");

try{
    $pdo = new PDO('sqlite:db.sqlite');
} catch (Exception $ex) {
    
}

$app->add(new Acme\ShowCommand($dbAdapter));

$app->run();
